services:
  ubuntu-sshd:
    build: .  # Usa o Dockerfile local para construir a imagem
    container_name: ubuntu-sshd-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:2222:22"  # Mapeia a porta 2222 do host para a porta 22 do contêiner
      - "8080:80"  # Mapeia a porta 8080 do host para a porta 80 do contêiner
